services:
  build:
    environment:
      HOSTUID: ${HOSTUID}
      HOSTGID: ${HOSTGID}
      VERSION: ${VERSION}
    image: andy5995/linuxdeploy:v2-focal
    platform: ${PLATFORM:-linux/amd64}
    volumes:
      - $PWD:$WORKSPACE
    working_dir: $WORKSPACE
    command: $SCRIPT
    restart: "no"
