name: linuxdeploy dependencies docker image
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: trunk
    paths:
    - 'dependencies.dockerfile'
    - '**workflows/deps-linuxdeploy-docker.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 11 17 * *'

jobs:
  build-dependencies-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64"]
      fail-fast: false
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - if: ${{ matrix.platform != 'linux/amd64' }}
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: andy5995
          password: ${{ secrets.UNCLE_ANDY_DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build Image
        run: |
          docker build . \
            --platform ${{ matrix.platform }} \
            -t andy5995/linuxdeploy:dependencies-latest \
            -f ./dependencies.dockerfile --push
