name: linuxdeploy dependencies docker image
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: trunk
    paths:
    - 'dependencies.dockerfile'
    - '**/**/deps-linuxdeploy-docker.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 11 17 * *'

jobs:
  build-dependencies-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: andy5995
          password: ${{ secrets.UNCLE_ANDY_DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          append: |
            - platforms: linux/amd64
            - platforms: linux/arm64
            - platforms: linux/arm/v7
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dependencies.dockerfile
          push: true
          tags: andy5995/linuxdeploy:dependencies-latest
