name: linuxdeploy docker image

on:
  push:
    branches: trunk
    paths:
    - 'Dockerfile'
    - '**docker.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 11 18 * *'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: andy5995
          password: ${{ secrets.UNCLE_ANDY_DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386,linux/armv7
          push: true
          tags: andy5995/linuxdeploy:latest
          cache-from: type=registry,ref=andy5995/linuxdeploy:buildcache
          cache-to: type=registry,ref=andy5995/linuxdeploy:buildcache,mode=max
