name: Test Action
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: v2
    paths:
    - '.env'
    - 'docker-compose.yml'
    - '**test.yml'
  pull_request:
    branches: v2
    paths:
    - '.env'
    - 'docker-compose.yml'
    - '**test.yml'

env:
  VERSION: container-test

jobs:
  test-rmw:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout rmw
        uses: actions/checkout@v4
        with:
          repository: theimpossibleastronaut/rmw

      - if: ${{ ! contains(matrix.platform, 'amd64') }}
        uses: docker/setup-qemu-action@v3

      - name: Set variables
        run: |
          if [ -z "$VERSION" ]; then
            echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Install docker-compose
        run: |
          #sudo apt update
          #sudo apt upgrade -y
          sudo apt install -y docker-compose

      - name: Checkout rmw
        uses: actions/checkout@v4
        with:
          path: _linuxdeploy_test

      - name: Build AppImage
        run: |
          export HOSTUID=$(id -u) HOSTGID=$(id -g)
          docker-compose -f _linuxdeploy_test/docker-compose.yml run --rm build
        env:
          SCRIPT: 'packaging/appimage/pre-appimage.sh'
          PLATFORM: ${{ matrix.platform }}

      - name: Create sha256sum
        run: |
          IMAGE_FILENAME=$(basename `find out/*AppImage`)
          echo "IMAGE_FILENAME=$IMAGE_FILENAME" >> $GITHUB_ENV
          cd out
          sha256sum "$IMAGE_FILENAME" > "$IMAGE_FILENAME.sha256sum"

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_FILENAME }}
          path: ./out/*
          if-no-files-found: error
