name: Test Action

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    env:
      APPDIR: '${{ github.workspace }}/AppDir'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use action from self
        id: linuxdeploy
        uses: ./
        with:
          platform: ${{ matrix.platform }}
          install_commands: |
            sudo apt install -y libncursesw5-dev
          build_commands: |
            export -p
            git clone --depth 1 https://github.com/theimpossibleastronaut/rmw
            cd rmw
            meson setup _build -Dprefix=/usr
            cd _build
            ninja
            meson install --destdir=$APPDIR --skip-subprojects
          linuxdeploy_args: |
            -d rmw/packaging/rmw.desktop \
            --icon-file=rmw/packaging/rmw_icon_32x32.png \
            --icon-filename=rmw \
            --executable=$APPDIR/usr/bin/rmw \
            --appdir=$APPDIR \
            -o appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: rmw_appimage_${{ matrix.platform }}
          path: ./out/*
          if-no-files-found: error
